
import javafx.scene.image.Image;

public class Cell {

    private CellType type;
    private Image image;

    public Cell(CellType type) {
        this.type = type;
    }

    /**
     * loads a cell from a string as generated by toString(), used to load data
     * from persistent storage.
     *
     * @param cellData the string generated by toString().
     */
    public Cell(String cellData) {
        String[] splitData = cellData.split("#");
        type = CellType.valueOf(splitData[0]);
    }

    /**
     * saves the cell as a string from which a copy can later be loaded using
     * the Cell(String) constructor, used to save the cell to a text file.
     *
     * @return a string containing all information needed to load a copy of this cell.
     */
    @Override
    public String toString() {
        String cellData = "";
        if (type != null) {
            cellData += type;
        }
        return cellData;
    }

    public CellType getType() {
        return this.type;
    }

    public Image getImage() {
        return this.image;
    }

    public void setImage(Image image) {
        this.image = image;
    }

}
