
import javafx.scene.image.Image;

/**
 * A dumb targeting enemy. Enemy that always moves in a straight line towards
 * the player, regardless of obstacles.
 *
 * @author Ahmed Ajaj
 * @version 1.0
 */
public class DumbTargetingEnemy extends TargetingEnemy {

    private int xDifference;
    private int yDifference;

    /**
     * This method constructs a dumb targeting enemy using the constructor in
     * the super class
     *
     * @param x The initial x co-ordinate.
     * @param y The initial y co-ordinate.
     * @param image The image used to present the moveable object
     * @param player Reference to the player
     */
    public DumbTargetingEnemy(int x, int y, Player player) {
        super(x, y, player);
    }

    /**
     * loads a targetingEnemy character from a string as generated by toString(), used to load data
     * from persistent storage.
     *
     * @param dumbEnemyData the string generated by toString().
     * @param player the player in the level to which this enemy is being added to.
     */
    public DumbTargetingEnemy(String dumbEnemyData, Player player) {
        super(dumbEnemyData);
        this.player = player;
    }

    /**
     * saves the dumbTargetingEnemy character as a string from which a copy can later be loaded using
     * the dumbTargetingEnemy(String) constructor, used to save the dumbTargetingEnemy character to a text file.
     *
     * @return a string containing all information needed to load a copy of this dumbTargetingEnemy character.
     */
    @Override
    public String toString() {
        return EnemyType.DUMB_TARGETING + ";" + super.toString();
    }

    /**
     * This method calculates the difference between the x coordinates of the
     * enemy and the player
     *
     * @return The difference between the x coordinates of the enemy and the
     * player
     */
    public int xDifference() {
        if (player.getXCoord() < getXCoord()) {
            xDifference = getXCoord() - player.getXCoord();
        } else {
            xDifference = player.getXCoord() - getXCoord();
        }
        return xDifference;
    }

    /**
     * This method calculates the difference between the y coordinates of the
     * enemy and the player
     *
     * @return The difference between the y coordinates of the enemy and the
     * player
     */
    public int yDifference() {
        if (player.getYCoord() < getYCoord()) {
            yDifference = getXCoord() - player.getYCoord();
        } else {
            yDifference = player.getYCoord() - getYCoord();
        }
        return yDifference;
    }

    /**
     * This method calculates the direction the dumb targeting enemy will move
     * in regardless of the validity of the move or obstacles
     *
     * @param board Reference to the board class
     * @return The direction the enemy will move in
     */
    public Direction calculateDirection(Board board) {
        if (xDifference() >= yDifference()) {
            if (player.getXCoord() > getXCoord()) {
                return Direction.RIGHT;
            } else if (player.getXCoord() < getXCoord()) {
                return Direction.LEFT;
            } else {
                if (player.getYCoord() > getYCoord()) {
                    return Direction.DOWN;
                } else if (player.getYCoord() < getYCoord()) {
                    return Direction.UP;
                }
            }
        } else {
            if (player.getYCoord() > getYCoord()) {
                return Direction.DOWN;
            } else if (player.getYCoord() < getYCoord()) {
                return Direction.UP;
            } else {
                if (player.getXCoord() > getXCoord()) {
                    return Direction.RIGHT;
                } else if (player.getXCoord() < getXCoord()) {
                    return Direction.LEFT;
                }
            }
        }
        return null;
    }
}
