
import javafx.scene.image.Image;

/**
 * a straight line enemy: Enemy that moves in a straight line towards the player
 * @author Ahmed Ajaj
 * @version 1.0
 */

public class StraightLineEnemy extends Enemy {

    private Direction direction;

    /**
     * This method contructs a straight line enemy using the constructor in the super class
     * with the addition of direction as a parameter
     * @param x The initial x co-ordinate.
     * @param y The initial y co-ordinate.
     * @param direction The direction that the enemy will move in
     * @param image The image used to present the moveable object
     */
    public StraightLineEnemy(int x , int y , Direction direction) {
        super(x, y);
        this.direction = direction;
    }

    /**
     * loads a StraightLineEnemy character from a string as generated by toString(), used to load data
     * from persistent storage.
     *
     * @param straightData the string generated by toString().
     */
    public StraightLineEnemy(String straightData) {
        super(straightData);
        String straightObjData = straightData.split(";")[3];
        String[] splitData = straightObjData.split("/");
        direction = Direction.valueOf(splitData[0]);
    }

    /**
     * saves the StraightLineEnemy character as a string from which a copy can later be loaded using
     * the StraightLineEnemy(String) constructor, used to save the StraightLineEnemy character to a text file.
     *
     * @return a string containing all information needed to load a copy of this StraightLineEnemy character.
     */
    @Override
    public String toString() {
        String straightData = EnemyType.STRAIGHT_LINE + ";"
                + super.toString() + ";";
        straightData += direction;
        return straightData;
    }
    
    /**
     * This method calculates the direction the smart targeting enemy will move in
     * while the move is valid and meets the criteria in the isMoveValid method
     * @param board Reference to the board class
     * @return The direction the enemy will move in
     */
    public Direction calculateDirection(Board board) {
        Cell nextCell = super.getNextCell(this.direction, board);
        if (!super.isMoveValid(nextCell)) {
            switch (direction) {
                case LEFT:
                    this.direction = Direction.RIGHT;
                    break;
                case RIGHT:
                    this.direction = Direction.LEFT;
                    break;
                case UP:
                    this.direction = Direction.DOWN;
                    break;
                case DOWN:
                    this.direction = Direction.UP;
                    break;
                default: //do nothing
                    break;
            }
        }

        return this.direction;
    }
}
